blueprint:
  name: Anti-theft Light Control
  description: Turns on a switch (like a HomeWizard Energy Socket) randomly within 20 minutes after sunset and off at a random time around a target time.
  domain: automation
  input:
    switch_target:
      name: Switch
      description: The switch to control
      selector:
        entity:
          domain: switch

    off_time:
      name: Off time
      description: The target time to turn the switch off (±22 minutes)
      default: "23:00:00"
      selector:
        time:

trigger:
  - platform: sun
    event: sunset
    offset: "-00:15:00"

condition: []

action:
  - variables:
      random_on_offset: "{{ range(0, 20*60)|random }}"
      random_off_offset: "{{ range(-15*60, 20*60)|random }}"
      off_time_input: !input off_time
      on_delay: "{{ random_on_offset }}"
  - delay:
      seconds: "{{ on_delay }}"
  - service: switch.turn_on
    target:
      entity_id: !input switch_target

  - variables:
      off_delay_seconds: >
        {% set t = off_time_input.split(':') %}
        {% set now = now() %}
        {% set base = now.replace(hour=t[0]|int, minute=t[1]|int, second=t[2]|int, microsecond=0) %}
        {% if base < now %}
          {% set base = base + timedelta(days=1) %}
        {% endif %}
        {% set final = base + timedelta(seconds=random_off_offset) %}
        {{ (final - now).total_seconds() | int }}
  - delay:
      seconds: "{{ off_delay_seconds }}"
  - service: switch.turn_off
    target:
      entity_id: !input switch_target