blueprint:
  name: Switch On at Specified Time
  description: >
    Turns on a selected switch at a specified time each day.
  domain: automation
  input:
    switch_target:
      name: Switch
      description: The switch to turn on
      selector:
        entity:
          domain: switch
    on_time:
      name: On Time
      description: The time to turn the switch on
      default: "20:00:00"
      selector:
        time:

trigger:
  - platform: time
    at: !input on_time

condition: []

action:
  - service: switch.turn_on
    target:
      entity_id: !input switch_target

mode: