blueprint:
  name: Turn ON Airco (Season-Aware)
  description: Turns on an airco for heating (winter) when cold enough or cooling (summer) when warm enough, with sufficient solar power
  domain: automation
  input:
    climate_entity:
      name: Climate Entity
      description: The climate entity to turn on
      selector:
        entity:
          domain: climate
    temperature_sensor:
      name: Temperature Sensor
      description: The temperature sensor for this room
      selector:
        entity:
          domain: sensor
    season_mode:
      name: Season Mode
      description: Select heating (winter) or cooling (summer) mode
      default: cooling
      selector:
        select:
          options:
            - label: "Heating (Winter)"
              value: "heating"
            - label: "Cooling (Summer)"
              value: "cooling"
    trigger_temp:
      name: Trigger Temperature
      description: For cooling mode - temperature above which airco turns on. For heating mode - temperature below which airco turns on
      default: 21
      selector:
        number:
          min: 15
          max: 25
          step: 0.5
    required_power_surplus_sensor:
      name: Required Power Surplus Sensor
      description: Sensor with required power surplus for airco
      selector:
        entity:
          domain: sensor
    power_approximation_sensor:
      name: Power Approximation Sensor
      description: Power approximation sensor
      selector:
        entity:
          domain: sensor
    priority_temp_sensor:
      name: Priority Temperature Sensor
      description: For cooling mode - highest temp among inactive aircos. For heating mode - lowest temp among inactive aircos
      selector:
        entity:
          domain: sensor
    disable_switch:
      name: Disable Airco Input Boolean
      description: input_boolean to disable this automation
      selector:
        entity:
          domain: input_boolean
    airco_turning_on_boolean:
      name: Airco Turning On Input Boolean
      description: input_boolean to avoid multiple triggers (race conditions)
      selector:
        entity:
          domain: input_boolean
    related_airco_automations:
      name: Related Airco Automations
      description: List of related automation entity_ids
      selector:
        entity:
          domain: automation
          multiple: true
    active_aircos_sensor:
      name: Active Aircos Sensor
      description: Sensor that counts the number of active aircos
      selector:
        entity:
          domain: sensor

variables:
  temperature_sensor: !input temperature_sensor
  priority_temp_sensor: !input priority_temp_sensor
  climate_entity: !input climate_entity
  active_aircos_sensor: !input active_aircos_sensor
  power_approximation_sensor: !input power_approximation_sensor
  required_power_surplus_sensor: !input required_power_surplus_sensor
  season_mode: !input season_mode
  trigger_temp: !input trigger_temp

trigger:
  - platform: numeric_state
    entity_id: !input temperature_sensor
    above: !input trigger_temp
    id: temp_above
  - platform: numeric_state
    entity_id: !input temperature_sensor
    below: !input trigger_temp
    id: temp_below
  - platform: numeric_state
    entity_id: !input power_approximation_sensor
    below: !input required_power_surplus_sensor

condition:
  - condition: state
    entity_id: !input disable_switch
    state: "off"
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ season_mode == 'cooling' }}"
          - condition: trigger
            id: temp_above
          - condition: numeric_state
            entity_id: !input temperature_sensor
            above: !input trigger_temp
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ season_mode == 'heating' }}"
          - condition: trigger
            id: temp_below
          - condition: numeric_state
            entity_id: !input temperature_sensor
            below: !input trigger_temp
  - condition: numeric_state
    entity_id: !input power_approximation_sensor
    below: !input required_power_surplus_sensor
  - condition: state
    entity_id: !input climate_entity
    state: "off"
  - condition: template
    value_template: >
      {% if season_mode == 'cooling' %}
        {{ (states(temperature_sensor)|float(0)) >= (states(priority_temp_sensor)|float(100)) }}
      {% else %}
        {{ (states(temperature_sensor)|float(100)) <= (states(priority_temp_sensor)|float(0)) }}
      {% endif %}
  - condition: state
    entity_id: !input airco_turning_on_boolean
    state: "off"

action:
  - service: input_boolean.turn_on
    target:
      entity_id: !input airco_turning_on_boolean
  - delay: "00:00:05"
  - service: climate.turn_on
    target:
      entity_id: !input climate_entity
  - service: climate.set_hvac_mode
    target:
      entity_id: !input climate_entity
    data:
      hvac_mode: >
        {% if season_mode == 'heating' %}
          heat
        {% else %}
          cool
        {% endif %}
  - service: notify.email_gmail
    metadata: {}
    data:
      title: >
        {{ climate_entity }} turned ON ({{ season_mode }} mode)
      message: |
        {{ climate_entity }} turned ON in {{ season_mode }} mode.
        Current temperature: {{ states(temperature_sensor) }}°C
        Total active aircos: {{ (states(active_aircos_sensor)|int) + 1 }}
        Power Approximation: {{ states(power_approximation_sensor) }}W
        Required: {{ states(required_power_surplus_sensor) }}W
  - delay: "00:02:30"
  - service: input_boolean.turn_off
    target:
      entity_id: !input airco_turning_on_boolean
  - repeat:
      for_each: !input related_airco_automations
      sequence:
        - service: automation.trigger
          target:
            entity_id: "{{ repeat.item }}"
          data:
            skip_condition: false

mode: single
