blueprint:
  name: Turn OFF Airco (Season-Aware)
  description: >
    Turns off an airco when conditions are met: for cooling mode when temperature drops or insufficient power; for heating mode when temperature rises or insufficient power.
  domain: automation
  input:
    temperature_sensor:
      name: Temperature Sensor
      description: The sensor that measures the temperature in the target room
      selector:
        entity:
          domain: sensor
    power_approximation_sensor:
      name: Power Approximation Sensor
      description: >
        The sensor that approximates the available solar power (negative values mean power surplus).
        This is used to trigger turning off the airco when the generated solar power is insufficient.
      selector:
        entity:
          domain: sensor
    climate_entity:
      name: Climate Entity
      description: The climate entity for the airco to turn off
      selector:
        entity:
          domain: climate
    season_mode:
      name: Season Mode
      description: Select heating (winter) or cooling (summer) mode
      default: cooling
      selector:
        select:
          options:
            - label: "Heating (Winter)"
              value: "heating"
            - label: "Cooling (Summer)"
              value: "cooling"
    off_temp:
      name: Off Temperature Threshold
      description: For cooling mode - airco turns off if temperature drops below this. For heating mode - airco turns off if temperature rises above this
      default: 19
      selector:
        number:
          min: 15
          max: 25
          step: 0.5
    priority_active_temp_sensor:
      name: Priority Active Temperature Sensor
      description: For cooling mode - lowest temp among active aircos. For heating mode - highest temp among active aircos
      selector:
        entity:
          domain: sensor
    airco_turning_off_boolean:
      name: Airco Turning Off Boolean
      description: The input_boolean helper that shows if any airco is currently being turned off (to avoid multiple triggers).
      selector:
        entity:
          domain: input_boolean
    disable_airco_xyz_boolean:
      name: Disable Airco XYZ Boolean
      description: >
        An input_boolean that, when ON, disables this automation.
        This is useful for manual control or maintenance.
      selector:
        entity:
          domain: input_boolean
    related_airco_automations:
      name: Related Airco Automations
      description: List of related automation entity_ids
      selector:
        entity:
          domain: automation
          multiple: true

variables:
  climate_entity: !input climate_entity
  temperature_sensor: !input temperature_sensor
  priority_active_temp_sensor: !input priority_active_temp_sensor
  power_approximation_sensor: !input power_approximation_sensor
  season_mode: !input season_mode
  off_temp: !input off_temp

triggers:
  - entity_id: !input temperature_sensor
    below: !input off_temp
    trigger: numeric_state
    id: temp_below_trigger
  - entity_id: !input temperature_sensor
    above: !input off_temp
    trigger: numeric_state
    id: temp_above_trigger
  - entity_id: !input power_approximation_sensor
    above: 0
    trigger: numeric_state
    id: power_insufficient_trigger
conditions:
  - alias: The airco is not disabled
    condition: state
    entity_id: !input disable_airco_xyz_boolean
    state: "off"
  - alias: The airco is currently ON
    condition: template
    value_template: "{{ states(climate_entity) != 'off' }}"
  - alias: Season-aware temperature and power conditions
    condition: or
    conditions:
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ season_mode == 'cooling' }}"
          - condition: trigger
            id: temp_below_trigger
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ season_mode == 'heating' }}"
          - condition: trigger
            id: temp_above_trigger
      - condition: and
        conditions:
          - condition: trigger
            id: power_insufficient_trigger
          - condition: template
            value_template: >-
              {% if season_mode == 'cooling' %}
                {{ (states(temperature_sensor)|float(0)) <= (states(priority_active_temp_sensor)|float(100)) }}
              {% else %}
                {{ (states(temperature_sensor)|float(100)) >= (states(priority_active_temp_sensor)|float(0)) }}
              {% endif %}
          - condition: state
            entity_id: !input airco_turning_off_boolean
            state: "off"
actions:
  - target:
      entity_id: !input airco_turning_off_boolean
    action: input_boolean.turn_on
    data: {}
  - delay: "00:00:05"
  - target:
      entity_id: !input climate_entity
    action: climate.turn_off
    data: {}
  - data:
      title: >
        {{ climate_entity }} turned OFF ({{ season_mode }} mode)
      message: |
        {{ climate_entity }} turned OFF from {{ season_mode }} mode.
        Current temperature: {{ states(temperature_sensor) }}°C
        Total active aircos: {{ (states('sensor.active_aircos')|int) - 1 }}
        Power Approximation: {{ states(power_approximation_sensor) }}W
    action: notify.email_gmail
    metadata: {}
  - delay: "00:02:30"
  - target:
      entity_id: !input airco_turning_off_boolean
    action: input_boolean.turn_off
    data: {}
  - repeat:
      for_each: !input related_airco_automations
      sequence:
        - service: automation.trigger
          target:
            entity_id: "{{ repeat.item }}"
          data:
            skip_condition: false
mode: single

